import java.util.*;

public class Problem1 {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
     //   String input = scanner.next();
       // input=scanner.next();
     //   System.out.println(input);
String input=">Rosalind_6725\n" +
        "GTCCGCCGAGTGAGAGGTGGATCGTGGGAGTCCCTACCTGGTTCTCTATGTCGTTTACAG\n" +
        "GAAGACATACTAGCCTGCCGGTGAGTCTATGGTATAGCGGAGTGGAACTTGAAACTGCGG\n" +
        "ATACAGCGTTCCCGCTAGCTGGCTTCACGTAGGATGGTAGCCGAACCACTAATTGTACCG\n" +
        "GTCGAATGCAGTGTCCCTTTTCAATATCTCGGGGTTACTTACTGTTGGCTGTTTAATGGC\n" +
        "ATGTCTCACGTCTATTCTTGCAAATCTAATATCTCTATCACGCTCTGCGTAGGAGTTGTA\n" +
        "ACTTGCTACCTAGCTTGTCGCACTAGCAAGAAGGTATTGGGTCGTGGTCCCCTTGGAGCC\n" +
        "CTTTCGTTTGAGTGGCAGACAGCATAGCCAAGCTACCGTTTCCTCCAGTACAACCATTTG\n" +
        "GTTTTTGGAAACGGGGCTTATTGGGATATTCGAGGTGACCCGCGCTAGCGCAATGCGTAC\n" +
        "GACAAACCGCAATACTTCGTAAATACAAGTCTCCACGAAGCTAAGTAGCATAATACTAGG\n" +
        "AGGGTCTACACGAGTGTAAGAGGACTCGTTGGTATGAACCTCCGGAGCGTACTAAAGGAC\n" +
        "CCGTCTTCAACACTCTTAGGGCCACTCCTTGAGCGGGACCGACAGATATTTTGTTGCACC\n" +
        "CGTCTGTCGTCATGGAACCTCGGTGTAATGTGGGGCCGTCCAGCGTGACATACACGAATT\n" +
        "TGTGCAGCACCCGGTTAAAAGCGGTATCACGATACGGAGACGGTTGTGGAATGAGTCTCC\n" +
        "GATTCGAATTATCAAATTCTGTACAATCTATTTGGCTTGACCAAGCCCCGCTGCCATGAA\n" +
        "ACATGCTTGACT\n" +
        ">Rosalind_7577\n" +
        "AGTTTACAAGAAGTGGCGCACCGGCCCGAAGGAGATCTCAGGTGTAGATTAGGTCCTGTG\n" +
        "GGGTGATAACCGGCTTATAGGAACCAACTTAAAGGGTGTTCTCAGGCCTCGGCCCCTGTT\n" +
        "CTTCGGGGCTTTACTGTGTGAAAGTTCTACGGAAGCTGTGGTCACAAACCCTTGTCATGC\n" +
        "CTGTACGGCGTGAATAAGCGTGATCAGCCATGAGACCCTGGTCCACTTCCGGTATTAGTT\n" +
        "ACATCACCCGCACTCATCCAGTCAAGAAGAAAGCCTCAGGCATAATGACAGACATTCAGG\n" +
        "CTACAGACGTAGACTGGGCTTTTAGCCAATATTGAAGATGAGGCAAGGGGACGACGTCCC\n" +
        "GCGGTACCTTATCTCTCCGGTTATATCTGAATGGTAGAAGGGGATAAATTCGCTGGAGGC\n" +
        "TGCGGCCTAATGCTTATAGGCGCAGTTGAAGGGTCATCTGCGAGGTCGCTGATGAGGCAG\n" +
        "GATTGTCTGTCCTCTCGAATCTCCACATGATAACCCGACACCGAACCCATAACCCCCGTT\n" +
        "TATGAATCATAATTGTCCGGTCCTAAATAATTTATGAACGTCACTAATTAAGCCATAGGT\n" +
        "GAACCCAAACTGAGGGGCAACGAGGCGTTGTGATCCAGATTCTCAAGAAGCGTGCTCCCC\n" +
        "TAGGCAAAAGGTTTGTACCAAGGCGGCGTCGGTAACCGTAACCTACTGAGCGCGGTCGAT\n" +
        "GTCTAATATCCGCGGGCTATTATGTGTCCGATCGACTTGCGTGTCGACTCTGGCCTCTTA\n" +
        "TAGGGTTCAATAGATATATCGGCATCATCAAGTATTGGCGACTTGAAATTCCAATTATCT\n" +
        "TTCTCAGTACAGCTATTCAAAGAAATTTGAAAAGGTATAATAGACAGTGCGTCGACAGCC\n" +
        "CAGCA\n" +
        ">Rosalind_2588\n" +
        "ATTCACCCAGTACGTCGAACCAGAAGTTCGAATAAGGTCCGCCTCTGAACGCTTATTGTC\n" +
        "AAAGTGCTAGCGTGGATGACGAAACTGACGGGACTATATCCAGAGTGCTATCTCTTCCCG\n" +
        "GACCTTAATTCGTTCAGCGAGTACAGGTCTGTGACATATCTAGTGATGAAGTCTAGAAAG\n" +
        "ACGTAACCCACATCTAATATGCTGTTTCGTTCCTTCCCCATGGCTCGAACATAAAATCTC\n" +
        "ATATTATCGTGAAGAGAGGGCGGTAGCGCTCCTGTCCTCTTTTGAGTCCAAGAATACTAC\n" +
        "TCGCAACCAAGGGAAAGGCCTGCTCGCGAACAGAAACTGTCAAGGGCTATCTGGGGAGCG\n" +
        "CCGCGGCAACGTTAAGAGTCCTGAACGGACGGTAATTCTCGAGCGACTGTCTCCCCTATT\n" +
        "CGCAGTAGGGAACATCATAATGTATTACATCCCCCTAGCTGAGTATGGGCCGCTCAGCTT\n" +
        "TTCGTCCCATTCCATAAGATCTCTGGTCCATTTACCTTTATCATCAGCACACCTCTTTAC\n" +
        "GAATTGAGTTCGAAGTAATTACTCTCTGTGACGGTTTTTGAGAGTGAGCACTTTGTAACG\n" +
        "GCAGTCCCCAGGGGGCACTCATATCTTGAAGATGCTAATGCAGTACGGTGTGCTACTACA\n" +
        "AGACCAGCGCATAGAAATTCGTGTACTTATGCGCGCCAGGGTGAATCGAGACAAAAGTAG\n" +
        "GGGAGGGATAGCTCGCGTCGCTCTCTATGTTGGTAGGGCGAGTTAAGGTACTGCGCACGG\n" +
        "TAGCCTGTGCACCGGTTACTGGCATGTCTTTGTGAGCATCTCACAACGCGAGGGATTCGA\n" +
        "GATTGCTTTGGGGCAGAGGTATGGTCGTGCACCGTCCTCAAAATAAGGACGCGCTGTGTG\n" +
        "CTGCGATTTAATTAAACATAGTGGCCTAAATTGTGCAGCA\n" +
        ">Rosalind_7939\n" +
        "TACTCGACGTATGAATAATCCCTGCAACTCTATACGACCAGGAAACGCGAGACGAGATCT\n" +
        "GGCGCGTACGTAGAACAGGCAGCCCACAGTGTTCCCGGGACCAGTGATGCAATTCAATGG\n" +
        "CAGATTTGAAGAGTGTGCCTAGGAAAGTGTATTTTCCATTACTGCCGGAGACTCTTTGCA\n" +
        "ATCCTACCATCTTGAAGGGACCCGACAGATGGTGAAATACTGTGGGGATCGACAGTCGCA\n" +
        "GGGGTCAGCGATTGACGGTCCTATTTGTCAGCTTGGGGAGATTAGGAAGAGTACCTTATC\n" +
        "GTACACACTGGTTGGTGGGACATTCGGTTTACTTAATAAATATCTACCAGGCAATCGAGT\n" +
        "CCCTCAGCAGTAGAGACTGTTAGCCGCTTCGCTGTCGTCTGTTAATGCTACTGATAACCA\n" +
        "CTTACTGAGGACCAGAAATGAGAGAGGATTTGGTAGGTTAACGCAGCCGTGGACTCGTAG\n" +
        "TGAATAAGTCAACGTTCACGCGTTGGTACAAACATCAGCCGCACTGCGAGCCAAAGGGCA\n" +
        "TATATGGCTATCCGGGCTTGCGAGTGGTTAAAGTGTACGAAGACGTTAGGCGATAGCTCT\n" +
        "CGCAAATCGAAGAAACCAGGCTCGTTGCCAGAAAACCTTCTCCGATCAAATGTTGCTGCG\n" +
        "TTGTTTCAACAAAATCTATTAGCGGGATCTCAAAGTCCCGTCCTGCGAAGGGAAGAAGGA\n" +
        "CGCATTACTTGCCGTTTGGGTATAGGGAGATGATCGGCCTAGGGCGGCAAATGACATTGA\n" +
        "ACTCACTGCATAAACTTTGGCAAAGTAAACCCGATACCCACGGGCAGACTCCTGTTGGGG\n" +
        "CTTTCTGCACCTGGCTTGGTGACCTCCAGACACTTGTACGATGTTAGGCTCTGACTCTAT\n" +
        "AGAAGCCTGCCGATATAGGTTATGTTCTGTCCCGTGCTTGACCATAAGCTTCCTACACAA\n" +
        "CG\n" +
        ">Rosalind_8084\n" +
        "TAATCCAGTTGAGACTTTAACCCAAAAGTGTATTTCACTCGCGCGACGAAGGACAGTGGA\n" +
        "CTAGTTCCGCCGTGGTTTCGGGATTTGGGCGCTCGGAATATACGCTAAGCTTAGATTTGC\n" +
        "CTCAAAAGGGAGATTTCTAAGACGAGGGGAACCAGACTAACTGCTAGGACATCTGTATTT\n" +
        "AATTCATCCTTATTGTCCACTGGCCGCTCAGGTCGATGGTGCCCATTGCAAGTGCTCTGC\n" +
        "TAAGTGGAAGGGGTAGAGTTGTCTTCACCGGTAGGTATGTAGATGGCTTATGGGGCCAAG\n" +
        "CTTTCAAAGATTTGCATCTCGCAGCAATCCACGGCCTTATGATGAAAGATACACCGGCCG\n" +
        "GGTGGAACGATCTGCTGAAATCTGGCGTTGTGTACACTTACCGCATTCATTGATACCATC\n" +
        "TCCTAACCCGGACGCATTCTAATTCTCGGCCCGACAGCTTGAAGACCCGTGGACGATTAG\n" +
        "AAATGCCCAGTTCCGTCCTGGCAATGCAGAAGGAGAGGTGCGTGTTTTGGACCTTTACAT\n" +
        "GAAGCGAGCTTCGCTAATGTCCCAAGGGGTTCCAAACCGATTCTTTGCGGATCCCGCTTG\n" +
        "CCATAAATATCGTTGCAGTCGACCCCTTTAAGTCGGCTGAGCCTGTTTTGGATTGCGTTG\n" +
        "AAGCAGTAGGCATTACACCTCACCTGGAGACTTTTACTGGGCTCATGACAATCTCCCAAT\n" +
        "AACATACCTGATTCGACGTCGACGGTAGACTCTTCCTGAATCGAGAATTTCTCCGGCAAG\n" +
        "TTGATAGGCCGACTGTCTGAACGTCTTTCTAGTAAGGCATGAGCCACTGTCGTACCTTTT\n" +
        "GTAGGTACCATATAGTGGCTACGTGGCGTAGCTGGGACTTCGTTGGAGGATGTCGGGCCG\n" +
        "CACTGCTTATCATCGAGCGGCGGGTTTACCGCTGGGTTAGGTGATTGCTCGCGGCACGAC\n" +
        "ATTTCACGCGG\n" +
        ">Rosalind_9760\n" +
        "TCAATGTCAATGTAGCATCAGTCACACCAAGATGCTCGGACACCAAATAGCATTTGCAGG\n" +
        "TCAGAAAGGGGCCGGACACTTATCCTTGAACGTTAGGGTGCAGGGACAGGATCGTACGGG\n" +
        "AACCTCTCACCTCACATTCTCCGTTTCAAGGATCTCGGTACCTATAACGCAGTTCTGCGC\n" +
        "TGGCGAACACAAGTGATCTATGTAACTATCGGTTAAAGCCAAGAAGGACATGTCATCAGG\n" +
        "ACTAAGACCACACGAACCCGCGCCCACTACATTAATTACTCATCTTTCTTACACGGTGAT\n" +
        "GGTCATTGGGCATTACTGTGACGTTGTTCATCCATTTCAACTCAACCTCATAGTCTCTGT\n" +
        "TAAAGAGCTCTATCGTAGAACTACATCGTACCAAGACGTCCATTTCCTGAGCAGATAATA\n" +
        "ATGTTTAGTGTCGTTGCTTGGAACATACTGAGTCTGCTGATGTGTAAGTGGCTGTTGTGT\n" +
        "GCGTATTCAGTTTTAACCCAAGTCTCCATACTTCACCGTTAACGCTGCTTACGCTTAACC\n" +
        "AAGCAGATTTCTCTAGTTAGGCTAAATTGTGAATGCCCGTAATATGAGGTAAATGTGTTG\n" +
        "GTAACTGTCATTGCCGCCAGAGCAATGCAACATAAGGAGGGCCGCAGATAGGTGCGGATA\n" +
        "AGGTGTAATGAAACGTAGAATGCTTCGCTGCCGTGGGCCAGACAATCTGATATACGCGAC\n" +
        "AACTCACGTGTAACCCTGTTCGAGATTGTTAATAACTGGCCCTCTTAGGCTGAGTGCCTG\n" +
        "GTCGTAGAGTATCTCCAGAAATTGTGTTCGAGGAGAATGCGGCGGCCTTGTACGACGAGG\n" +
        "GGATGATATCTCAATATCAGCATCAGAACAAGCTCGCCCTCAGAAGGGCAACTTAGCCTT\n" +
        "CTGTGTTCCATCACCCACCGAGGCTC\n" +
        ">Rosalind_7017\n" +
        "TCGTGGAATTAAGGTTCGATAAGGTGCATGCGTTTTCACTTCTGGTAATTTTGATTCGAG\n" +
        "ACATAGAGTGTTTCGCTTCGCATAGTGTTATGGCAAAGGATAGGTTTTATGGGGTGATCC\n" +
        "AGCCAAGTCCAATCAATGTTATCCTATTCTTAACTATACGATTCGAACGAAATCCTGTAG\n" +
        "ATACAAACATTATGTGTAACCAATACCGGAAATTATGGAGTCCGGGTGGCAAACCAGTGC\n" +
        "CGCTCGATATATATCGGTAAACATTGCCGATTTACTACGCCTGCATAAGATGATGTCTAT\n" +
        "TCATGTCCATCATGCGAAATCATATTGCGTATTCTATCTCGCCTACAGTCCCACTCCCAC\n" +
        "CCGAGTTCGAAGCCTCTTCAAACATCCTGGAAAGACGAAAAATAGCGAACGAGCTAAGTT\n" +
        "CTTTTCGTACCCTCATAGACGAACCCCAATGGTCGCCGTTTAAACTTCCCTTTAATGGTG\n" +
        "GGGGACCTGGCCTACATCAGATAGCTAGCTGGATTATGGAGGCATGGCCGTAGAGCGTAT\n" +
        "GGTTACTGGGTTTAGGCATCCGCTTGGTGACAAACACCAGTAATTTAGAACTTCGGTCAG\n" +
        "TGCGCACACTACCGTCATATAATATCTAGGTAGCCCCTGCTACTAAAAAGATATTAGCAC\n" +
        "AAACAGGACGTAACGGCAACTACCTTGGCAGACTCGTTTGAGAGTCCAGGCGTGTATGTG\n" +
        "AATTTTATGTGCCACATTTTACAGGAACCCAGTAGAGCTCTTTCCCGATGATGCGACTCC\n" +
        "ACTCCCCCTCCGGATATATGTTACCTTATAGCCCGAAATGAATAAACTGGTCTCGCAGTG\n" +
        "TTAATCAATGGGGTAAAGCGGTGGTATCCTGATCCACCGCTAGTACGATAGCGCAGATAT\n" +
        "CGCTCCTTTTCGTATGTAGCC\n";


        Map<String, String> map = inputOrganizer(input);
        Map<String, Double> gcMap = new HashMap<>();
        map.forEach(
                (key, value) -> {
                    long occ = 0;
                    for (int i = 0; i < value.length(); i++)
                        if (value.charAt(i) == 'C' || value.charAt(i) == 'G') occ++;
                    gcMap.put(key, (occ * 1.0 / value.length() * 100));
                }

        );
        final String[] maxId = new String[1];
        final Double[] max = {0.0};
        gcMap.forEach((key, value) -> {
            if(value> max[0]){
                max[0] =value;
                maxId[0] =key;}


         //   System.out.println(key + ": " + value);
        });
        System.out.println(maxId[0]);
        System.out.println(max[0]);


    }

    public static Map<String, String> inputOrganizer(String input) {
        String[] temp = input.split(">");
        String[] temp2 = Arrays.copyOfRange(temp, 1, temp.length);
        LinkedList<String> inputs = new LinkedList<>(Arrays.asList(temp2));
        Map<String, String> stringStringMap = new HashMap<>();

        for (String s : inputs) {
            String[] split = s.split("\n", 2);
            if (split.length < 2) continue;
            stringStringMap.put(split[0], split[1].replace("\n", ""));
        }
        return stringStringMap;
    }
}
