import java.util.Arrays;
import java.util.LinkedList;
import java.util.Scanner;

public class Problem4 {

    static final int ALPHABET_SIZE = 26;
    static class TrieNode {
        int id;
        static int lastId = 0;
        TrieNode[] children = new TrieNode[ALPHABET_SIZE];

        boolean isEndOfWord;
        TrieNode() {
            id = lastId++;
            for (int i = 0; i < ALPHABET_SIZE; i++)
                children[i] = null;
        }
    }

    static TrieNode root;


    static void insert(String key) {
        int level;
        int length = key.length();
        int index;
        TrieNode pointer = root;

        for (level = 0; level < length; level++) {
            index = key.charAt(level) - 'A';
            if (pointer.children[index] == null) {
                pointer.children[index] = new TrieNode();
                System.out.println(pointer.id + "->" + pointer.children[index].id + ":" + key.charAt(level));
            }

            pointer = pointer.children[index];
        }
        pointer.isEndOfWord = true;
    }
    public static void main(String args[]) {
     //   Scanner scanner = new Scanner(System.in);
      //  String input = scanner.nextLine();
String input="CATAACTAGATTCATGTTGATCTAATGCCCTGACTATTCAGATGACCCATAATAACTCACTGGCCCGCTGGTAGAGTATA\n" +
        "GTTACCTATACGATACTTGCAGGAAATTAGGGAAATATCAATTCGAGTCGTTTGCAAGGTACCAAACCAGATAGAACGGCT\n" +
        "CCCTGCTACCTCTAGGGTAAAGGGTTTTATTAGGTTCTGCTTTATCTCGGGGGCTCCACCACGTCATGACGGCTTGACTAAC\n" +
        "CCTATTACCTCCTTCGATGCACGCCACAAATCGACAAGCGCGGGGGCTCATTCAGTGCCCTAGGTTACTTAGCCTACGCTGGGAAGTTTGTGTGGCTA\n" +
        "TCCTGTTCGACCTGTAGTGGGTAAGCAGCGACTCATAAGGATTGTCACCGTTCGCAGGAGACTCTAATCAAGCGTATGTCTTATGGGA\n" +
        "CAGCGGCACGTTACTTGTATGAGATCCGCCAGGGCGAGGGATTCTATCGCCCAGTAACCCGCCGAAGGAAAGAACCCCTGTTATTAGCCCACTACTCC\n" +
        "CCAACCCATGAACCGTGGGGAATTGCTGGGTACAGTCGCACGGAAAGCTCTCCTCTTTGCTCCCTAGAACTAGAATCTCATTATTGCTGCCTG\n" +
        "AGGGAAGATAGACGGAATACAACCAGATTACAAAGGTAATCCTGTAACATTCAACGGACAATTAGGTATTTCGCCCCATAACGAGTATCATGATT\n" +
        "TTGTGCAATGTCCTATCTTCCACGCCCATGTTTTTCTAAGAAGACGCGGTGTATCTTTATAGCCGGTTCGGCTTGGCCGATA\n" +
        "CATTGAGAGTGCATAGAGGAAGGATGAATCAGCGGCGCGACCTATCTTTAAGTAGCCACGGCTCCACTTACGGGGAGATCTTTAACCTAGGAATAAACC\n" +
        "TAGAGCGCCAACTTATTGATGCAGTGATGCCCTTACAGCCGTGTACCAGGAAATTGGAGGCAGCTACGCTTTCATTTGACGTTACCTAAACTCT\n" +
        "GTGATGGCAATTGAGACATCTCATCATCTGGCAAATGGCTGCAGGGGCTGCCTCAGGAATCAGGGGATGACTGACCCTCAGCTAGCATTCATTGATTCT\n" +
        "TTTATGTGTGCTTAATGCGAATCCGCATGAACCTTCGCATGTAGGCTTACAGCAAAATTCGTTACAAGCCATTGATCCTCGGACCTATATCGTCAG\n" +
        "TAACGGAATACCAATCTTATGGTGTCATGTCACAGGGCAATAGAAGGCCTGCCAGTTAGTAAGGGATTGGTGGAGGGGAGA\n" +
        "GCTGTTAATCGCGTTAATGAACGTGAGGTGATAAGTCGACTGTGTGATAACTAATACCTCGTTTAGTAAAAATGATTCCCTCTCTATCAT\n" +
        "GGCCACATATTCTGTGCGAAAGGGGTACGATGCGGCTTCACCACTTCCCCCCATTGGTCTTCTCCGACTCCGCACAACTGCGGTTGTCA\n" +
        "TGGCCCGCACGAGAACACGCCGTATTCTAGCTACACTTATAGTAGATAGGTGTGCCACACACAGGTCATGCAGTAAAGGATCCGCAGTAGC\n" +
        "AACCTCTGAGTTAAAGATCAGAAGTTGGCCTCAAAAATGCAGACCACGAAGAGCTCTCTCTAGCTGTCTGACGAGAGGAAAGAGCCGCAC\n" +
        "GCGCTTCGAGTTAAAGACCGTTCTCGCTGAAGAGATCAGAGACTAGTGTAACCGTGTAGTGTAGGATCAATTCGTACTCGCGGGAGA\n" +
        "GTGACGCCCTACGCCAGCACGACTGCCTGCAGGCCAATAGTCTCGTGGCAGTCGCACAGGCAAGAACATCGCGTTCGTGCCAGACAAAACGT\n" +
        "CGACATACTGCATTCCGATTGCAGATTAAAACCTTGATGATGCGAGTCTTGGCTTTCGCAAGCTGTTGAAGCTACTCTCAGAGACCTCGACC\n" +
        "GGGCATTGCTCACAGGACCCGCCCAGAAGGAGCATATATAGACACGTCAGCTCGAGTGACCTAATTGCGAAATAGCTGGCTACTCCG\n" +
        "ACAATACGGGTATTCTGGTCGACCAAACTGTAAGAACCAGTTGCGCGAGTAAATCTAACTGCCAATTCCAGGTTGGTTTGCCCCCGA\n" +
        "ATGGACCGCCATCAAGTTGTAAAGAGCGTTCACGAATTTCCTAATTTTCAGGCTGTCTGATTGTACTTCAACGAGTTAAAATGCACCTAGGATTA\n" +
        "TTTGCCTCACCTATGTCTCAAAGTGGTTTTTGGTTGGCCATGGGTGTAAACCTCAAGCGCACCGGCGCTCTCAGTTTCCGGGATAGGTTATCTCAGGA\n" +
        "ACAAGTAGTGGGTATACGAAAGTGGGTACCAATCAATATCCGGCTTAATGTAGATTACCTTTCTCACAGAACCTGCCAGCACCTG\n" +
        "ATGTAGGATAATTATACGCGAACATAACCACTAGCGATTGGCCTGGGGGCGATCCAACCTTCCGGAGGTGGAACGAATCACACATT\n" +
        "AGCGCGATATAGCGCCCCTTTATGCGACGTAGTCTGACAGACCCTAATACGTGGATCCGAGGTACAATACTCCCTACAAATATTCAT\n" +
        "GGCCAACTAGACGGGGGGCAAGACTTGACATTGAAGGAGGCGGATTGGTGCGCGCGAGACAGGAGCTAGTATTTCGAAAATAAAAAGTAGATCTAGGC\n" +
        "GCTTGTCACAATAGCACCGGAGCGTTGGGTATCTCCACACCGGAACCCTAGTGCTAAGGATGGACTTTATCGTCGTTGCCAT\n" +
        "CCGTCAATATCGGCCTAGTTATTTGTCCGAGGTTCAGATAATCTCTAGTCTCGAACGAAACGAGCCCTCGTAAACGTCCTACCGAACAAGTAG\n" +
        "GCAGGAGCTTAGAATACAGTGCCCCATTGAATCTTATTAAGGTCCGAGGTATGGTTCGAGGTCGATCTTTAAGGAAGTCGC\n" +
        "AGAGGTTATCGACGGCTAGATTGCCTAGGCTTCTGAACCCGGTTGTAATAGTTATCTCGGTTAAGGGAGTTCTGTATGACGCAGCACTACGTCCC\n" +
        "CCTTTTAACACCGAATTATCAACAGCTTTTACTTCTTGCTCCTGATTATCTGCTCGGTCCTAAGAGATAAAAAAGTTCAGGCGAAT\n" +
        "ATCAGTAGCCTAATGATGGGGGGATAGGTCAATAGCGTGTCATATGTAACAGGGTTCATCTCTATGCAAATTTTTCCCGTCAGCGTCGCTAACTA\n" +
        "GAACTGGAATCTTGCAACCATCCGTTACGTTGACATGGGCTATACGCGATGGAGATGTCTATAGTACGCTGACAACGTCGGTTTGTGGT\n" +
        "TGATACAGCATGACACAGCCAACAGGCCTCAATTCATAAAGGGACCATGACTAAAAAAGTGCGCGAACAATATGGTCTAAGAACATTGTCAGGAGA\n" +
        "ATTCTTTCATAATATTTCCAGTTTTCCCTAATTGCGTCGGAGATCCCATGGAAACGGTGAATTCTACCCTAGAAGGGCACTGCTAACAAG\n" +
        "CAACTTGTGTCGAAGCCTCTGGTTTACTCTTGCTATACTTCGAAAAATTAATCTGAGAATTTACCGGGGCATGCGTAAAGA\n" +
        "GGCCTAGAACCGGTTATCCATGTTGCTTGACGACGCCGACGGTCTAGTGCGCCAAATCGTAGAGATTAGCCGTGTCATTACATTCGTGTTTGCATCCA\n" +
        "GAAATAATGTTCCTGTACGTGTAATAGTGTTTTTGTAATTCAGTGTGCCTCTACGAACCTACTGAGTTAATCGCCGTAAGATGCGCGGTGAATGGTTTA\n" +
        "GTCAATCAGCGAACAGGTAAGCCCCGAATAGATGCAGGGGTACGGATTCAGTACGGCGGTGAGTCAGCACATCGACGTCCATCCTATGAATTGAA\n" +
        "ACAATAAAATGCTTTCGCATTCCACCCGCCGATGGGTGGCGAAACACTCGACGTGGCTGTCTAGGATTAACTAAAACGAACCCATCGTTT\n" +
        "AGTTGCATTGGTCGACCTTGTCGGGGTTACCCAGCGTACAACAAACCTAACAATATAAACCCACTGTTTTCCCGTCGCTTCGACTTGTATTG\n" +
        "GCATCGAAGCGATTATGATCAGCTTCATCCCCGTTAATGCAGTCTACGTCTGACAATAGCGTACGAATCGATTCTCAAACATGGACGGAGTAATGAAT\n" +
        "CGCTTGCATCGGACGGATGCAGAATCCTAACTCCTGGGCTCGTTAATAGAACTTGACTGTCTGTATAAGCCTAGCTCCATCTTTCGGCTCCCC\n" +
        "CAGAGAATCCTAAAATGATAGGAATCCGCAAGCGGGAATCTAGAACAGACTATTATTATAGATCTGCGCGGATATGAGATGGAA\n" +
        "GTAATTAAACATTACCCCCGACCAGGCACGATCAGGTTTCGAAAGGCTGGGCTCCGCTCAAAGCGTTCAGGTCATGGGTCGTCGACACGCTCACTATTT\n" +
        "TGCATCACCGAGTTGTGATCTCTCCTTATGGTGGAGCTCCCTGCCGGAATGGTCTACGAACCGACGAAAACGTGCCCAAGAATCGTTGTG\n" +
        "GCATCTGGACAAAGGACACCCAGTGAAGTTATATCACTGGCTCGCAACGTCGGGATAATTAGAAGCACTCTAGCACCTTCC\n" +
        "GTGCTAGCCATAATATTCATCGTATCGGGACGCATGTCACCTTTTGTCAGTGGTTTTCTTGCTATGTTCAAGTTCCCACAATCCAGCTACGT\n" +
        "GTATTAAGGTATATGGATGACACTGGCAGCGTTTGGACCCAGTACTATTGTCCGACTTACGTTTCCACCGAGGCGGCGCGGGA\n" +
        "GTTCCGTCAACCTAAATAGTCTGCGGACGAGGTTGTACTACACGCCTGCCGTCCCAACGCCCAGCGAGGCATCACTGGTAGGCA\n" +
        "TCTGCGATGGTCCTCGTTGTCTGTGGTTTCGTTTACCATTGCTTGGGCCGATGGCACAGCTGGGTATATCAGCAAATATGGTACTCAAAGTTAAC\n" +
        "TTTTACACCAAAGCACACTACACTCCTCGCTTCGGGGCCGTCCTCAAGCTGTGGGTCCGTGCGGTGTCATCTGTAAGGTA\n" +
        "AGAATCTTAGATGTCGCCATTCTGTGCGTCCGCCGGCGACGACCCCCGCGGAACCTGAGGCCTTCATGTACTGTGCAGGCGG\n" +
        "ACTGCTTCGGTATAGCGAAAGCAATCGACACGGAGAATACTGATATATGCAATCACACTCTGATGAGCCCGCCTCTAGCTCTCCTGGGACATTAGC\n" +
        "GCACCGACTCAATTTGAGCGTAATCCTTCATCTGAAGATTGACGCGGTAGTGATATATAACACTTCTTTGTGAGACTGCAAACGCCCTCT\n" +
        "ACGTGTCATATAGTTGGGGTGTAGAAGTTCGAAACTCTAGAATATGTAAACAGCTGGAACGTGAAACACATAATCACGGT\n" +
        "ATCTTGCTGGATCATTAAAGCGACATGATGGAATCACGCAGGCAAATCCTACCTCTAATACTCTATTCCGGGTTGTTGTGTT\n" +
        "TCTGCGCGGCATCGTCACACCCGCGTACCCCCGCTTCAACGACAACCCTTATCTCGTATTTACTCGGTTAAAGTAAGTACGGGTT\n" +
        "TAAGCTGTGGAAATGAAAATACAATACTAATAATGCCACGCTAGAGCCATAATAGTTTGAAATGGAGTTTCATAGCGTCCTCCAATCC\n" +
        "CTCCCACTCTCGGAGTGCGCGATGTGTTTTACAGTCAATAGAGGGGTCCTTTAACAGAATGTACGGCGACTTCATCTGCGCGCCCTCACGTTCA\n" +
        "TAGGCACACGAGACGTAGAACAATGCTGGGGGCTCAGCAGGCATACATGTTCCACGTCTGGGCAGCAGCGCGGGCCGCAGATCAG\n" +
        "CTCCACTCCCCCTTCAGGGGATCGAGAACATTGAGTATACCCTTGTAATGGGCTCACGCGTCTACAATTGAACTTGAAAAGCGG\n" +
        "TGCCTATCACTCGAGATGGCCTGTCTGTGGACCCGCGTAACAGCGGTGATCGTTTCATACAACGCTATCACCCAGGAAGT\n" +
        "ATAACCTGACCTTGGGCGTAGGAATCCAGAGCAGCGGCTGGAGACGCTTTCATACGCATGCCTCCTCTTGAGGTCCTGCTA\n" +
        "GTTACCTCGTAAGAGGGTCTAAGGTTTAACTAACGCGATACGTCTCCATATAAACGGAGTCGCGGTAGCCCGAATATCACCC\n" +
        "GTGGAGGAGGGATGGGCAAATAGGTAGTATTTCTACGATCCAGCGGGGACGAGTAGGGGGGTAATTCCATGAGATTTCCATCAGACTT\n" +
        "GCCGGATCGTGATACGCCATAATTAACCCCTGCCCGCATTACCCTAAAGCTCCAGCTGGGCCGCGGTACCTGACTACTTGTGTTAAGAACGGTC\n" +
        "ACCATCAGTCAAGTTCGCTTGTGATATCCCCTCCCTGGCATGATCGTTCCTTCTAGGACAGGAAGCGGAACTTTTTCTTCTGAT\n" +
        "TGCTAGATACATTCGCGCGCCGCGGAGGGCGCCGGTCCCGCGAGTGTGCCGATATGGTAGCATCTGATGGCCGCTAAACCCTTGCGT\n" +
        "AAAGGCCGCTGAAATGGTTCACACCGTGGTCATGGGGCGGAACCTGCCACCCACTGCTAACATGTCTGGTAAGGAGGAGTTTTGGCC\n" +
        "ATGTTCAGAATTGCGTGAACGGCACATGCCTTAGTAACTTATCCGGTCACTCGGCGGGGGAAGTCAACGTAATTCGTGCGGTCGCTTTGATTCCTCA\n" +
        "TTCTTTTAGTGACGGGTTGAACAGTCATACTTCTAGGCCATCTTTGGTTACAGTTCTGCCGTCCGACCCTTAATAGCATTCAGAGTCCGATGGCCTTC\n" +
        "CGGTGTCGCCTTAGTGTAGGTTGATCAGGGGTTAGCGTTTCTCAAGATGGCATTTAGTGGTGATGCCCACTGAGGAGTCGGGCAGCCAAGCCCAC\n" +
        "AAGTTTACTTTAGGCAGCTCTTCCTTTTAGGCATCATATGTAAACTACAGCTGCCATTTTTGCTATCCTGAACGCCTGTA\n" +
        "ATGTTAGGATACTCGAACGGGAGTCACCCAACATTAATGACCTAGAGATTAGAATATAATATCTCAGATTCATTTTCACGTTTGCCGAAGCACGCAATA\n" +
        "TAGACGAGGTTTTCAACGTCAGAGGTGTAACAACCGAAAATGCAGGTGCGCGCCCAGAATAGGTAGTTAACTACTCGTGTGAAGGGGC\n" +
        "CTTTACCTACGGTCTCTTTGGTGGCGTTGATGTCCCGTTCCCCACCGGTCCCGGCGGCGGCCCCTCCTGCGAAATATTGAT\n" +
        "GCGATACACGTAATAAGGGGCTGCAAATCCACGCCCATCCGTAAAAGATTTAATTCACGGCACGTGCACTGTCTGTTTTTCAG\n" +
        "GCTCCGGCGATATCAGTCCAAGTATGAAATGGACGCCCTTGGTATGGCTGCTACCAAGAGGGCTAGGGCTCGTGACCACA\n" +
        "AGCTAGACCGTATAAAAGGTTTGATAATTAGTTCGAGAGCGATTACGTATTACTCTCATGAGGGGGACCCTAGTGGTTTCGGTGGCGAGATGGCTTCCG\n" +
        "CTTTCTGGCTAAATTATGGGCATCACGAAGACAAGCAATGGGTTGTGTCCCGGTAGTGCTGCGAGTTCATAACACCTCTGTATACTAATGG\n" +
        "CGACTGGCGGCTACTCTCGAGGTTTACCCTACCGACTTAGTGCAGCGTCGGACTGGCGGTTTGACGACCTTCGCATGGTGCAGGTAGCGTGTTAAA\n" +
        "AGAAACGCCGAAACATCCACGGAGCACCGACCGGGAGACGACGTGTCATTAATCGCCTTTCGTGAGCTACACGCAGAGGCTGAGTAAGAC\n" +
        "GCAGCGGCCAAATTACTGTCGGGCAGCCGGTTGGATATACTTACTAAGGTTTCTCAAAAGCTTAGGCGAAGGGACGCTCGAGGGTGCTCCGGAGCATGGT\n" +
        "TACAAAGCACTGACTCTCTCAAGTGGTTGGGAGAACAGCCCTGCAACCGTGACTTTGTCTGCCTCTATATCGACATCAGGTGACTGGATGCTCGC\n" +
        "ATGTGAAGCCCATATTGTCGGCTCTGAGCAGTTTAGTCTCAATATTGGCGTTTACGACTCTCACTCCCACCGGTTTCACTTCGATAGCCCTACT\n" +
        "GTAGCAATTTAGCCACACCACTTGGGCATCTCGGCAATCGCGCTGCGCACGGGCACTGCTAACCCGCGCCCAGCCCGCCTCGGCAAGACGA\n" +
        "CATCGCCGCACGGTCCAATGGCAATAATGTACGATCGTTCGACTAGGTTCAGGTGGACTCCCTACATTTGCATGGCAGGAATGG\n" +
        "GGCGGCTATTGATGCTTCGGCGCACCTGTCCGTTACACTCCGCCTGACTGGTTTATGATATATCGACTCCGGCTGAGCGCTACACGGGGCCTGGGTGT\n" +
        "TCGCAGCATACATAATCAGCTTGATCTCGATCATTTAGGACCTTCATAGGGGTCGCCTACAACCGTGGGAGCAGCCCGGATTT\n" +
        "TACAATAACTTGATTGCTTCTAACCGCAGATTCAAGGTTACCTCCGTTCTCCACACCTCAATCCTTTTCTGCCAGGCTTTTACGTAATAACAAAT\n" +
        "TCTTCACCATCGCTTTTTAGGGTTCTCACCTAAGGGAACACAAAGCAAAAGAGGCCTCGACGAATTGACTTAGGATCCGC\n" +
        "TCCTATACCCAACCTATGTATTTTGAACACATAGCATAGAAACCGTTAGTGGGGGTGAGGATTTTGCTCGCCTGGCTGCTATCGGTCGAGCC\n" +
        "GTGGTACAGCGCTTCGAACGTGAAAAGTCTGTGATAACCGTCATCCTGGTGGATGCTTTTGGGCATGATAGCTGGCGCTTTAGCCGCGTCATTGT\n" +
        "CCCTGGGTCTCAGCTAAAAGCTGTCAATTTCTTGGTGATCCTTGAGTGTCGCGTTCTCGAATCAGATGTCTAATGAGGAGGGCGATCCG\n" +
        "AACATGTTGACTAGTTAGGTCCGACTCGACCCTAGGTGCGACGGAGGGCCATGCCGCTGTGTCTGTTTGAGCCTTTTTGG\n" +
        "CTTCCGGCCCGGTCACAAGTTAATTACGTCAAGCCGGTGACACCTCCGAGCCGTCATATTGCCCCGTGCAGCTCTTAAGGGGGACTGGAGTATCC\n";
        String[] keys;
        keys = input.split("\n");

        root = new TrieNode();


        for (int i = 0; i < keys.length; i++) {
            insert(keys[i]);
        }


    }
}

